# Generated by Django 2.2.5 on 2019-09-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_auto_20190904_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employersdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employersdetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employersdetails',
            name='username',
        ),
    ]
