# Generated by Django 2.2.5 on 2019-09-05 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminPanel', '0003_auto_20190904_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('profile_pic', models.ManyToManyField(to='AdminPanel.Images')),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancersdetails',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='freelancersdetails',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='freelancersdetails',
            name='userid',
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='EmployersDetails',
        ),
        migrations.DeleteModel(
            name='FreelancersDetails',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skill',
            field=models.ManyToManyField(to='AdminPanel.Skills'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ManyToManyField(to='AdminPanel.Categories'),
        ),
    ]
