# Generated by Django 2.2.5 on 2019-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_auto_20190905_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ManyToManyField(null=True, to='AdminPanel.Images'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='skill',
            field=models.ManyToManyField(null=True, to='AdminPanel.Skills'),
        ),
    ]
