# Generated by Django 2.2.5 on 2019-09-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_auto_20190905_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_freelancer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
