# Generated by Django 2.2.5 on 2019-09-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_auto_20190906_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='userid',
        ),
    ]
