'''Declaring some Global Variable'''
MESSAGE = "Message"
ERROR = "Error"
STATUS = "Status"
UPDATE_MESSAGE = "Record updated"
INSERT_MESSAGE = "Record inserted"
OPERATION = "Operation"
INFO = "info ================= "
ERROR_MSG = "error ================= "
SUCESS = "Request sucessfully completed"